baseURL = "http://gabrielsargeant.com/"
title = "Gabriel Sargeant"
theme = "smol"
uglyurls = true
summaryLength = 90

[Author]
    name = "Gabriel Sargeant"
    

[menu]  
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts.html"
        weight = 2 

    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags.html"
        weight = 2 

    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/posts/about.html"
        weight = 1 
    
    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/posts/contact.html"
        weight = 1 

    [[menu.main]]
        identifier = "interactiveStuff"
        name = "Interactive Stuff"
        url = "/posts/applist.html"
        weight = 0 

# Footer
    [[menu.footer]]
        name = "Github"
        url = "https://github.com/gabesargeant"
        weight = 1 

#Deployment configuration

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "default"

URL = "s3://5b4b535f-e208-47fe-a30c-551a7d7800f3?region=ap-southeast-2"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "E1EUL69ZEEK66P"

[[deployment.matchers]]
# Cache static assets for 20 years.
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true

